<!-- Projeto Desenvolvido na Data Science Academy - www.datascienceacademy.com.br -->
# <font color='blue'>Data Science Academy</font>
## <font color='blue'>Data Science Para Análise Multivariada de Dados</font>
## <font color='blue'>Projeto 2 - Parte 1 - Pré-Processamento</font>
### <font color='blue'>Seleção de Modelos de Machine Learning em Análise Multivariada com Dados Anonimizados</font>

### Instalando e Carregando Pacotes

In [1]:
# Para atualizar um pacote, execute o comando abaixo no terminal ou prompt de comando:
# pip install -U nome_pacote

# Para instalar a versão exata de um pacote, execute o comando abaixo no terminal ou prompt de comando:
# !pip install nome_pacote==versão_desejada

# Depois de instalar ou atualizar o pacote, reinicie o jupyter notebook.

# Instala o pacote watermark. 
# Esse pacote é usado para gravar as versões de outros pacotes usados neste jupyter notebook.
!pip install -q -U watermark

In [2]:
# Imports
import pandas as pd
import numpy as np
import pickle

In [3]:
# Versões dos pacotes usados neste jupyter notebook
%reload_ext watermark
%watermark -a "Data Science Academy"

Author: Data Science Academy

## Carregando os Dados

In [4]:
# Carregando os dados
df_dsa = pd.read_csv("dados/dataset.csv")

In [5]:
# Shape
df_dsa.shape

(11500, 179)

In [6]:
# Visualizando alguns registros
df_dsa.head()

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X170,X171,X172,X173,X174,X175,X176,X177,X178,LABEL_TARGET
0,135,190,229,223,192,125,55,-9,-33,-38,...,-17,-15,-31,-77,-103,-127,-116,-83,-51,False
1,386,382,356,331,320,315,307,272,244,232,...,164,150,146,152,157,156,154,143,129,True
2,-32,-39,-47,-37,-32,-36,-57,-73,-85,-94,...,57,64,48,19,-12,-30,-35,-35,-36,False
3,-105,-101,-96,-92,-89,-95,-102,-100,-87,-79,...,-82,-81,-80,-77,-85,-77,-72,-69,-65,False
4,-9,-65,-98,-102,-78,-48,-16,0,-21,-59,...,4,2,-12,-32,-41,-65,-83,-89,-73,False

## Análise Exploratória e Limpeza de Dados

In [7]:
# Categorias da variável alvo
df_dsa.LABEL_TARGET.value_counts()

LABEL_TARGET
False    9200
True     2300
Name: count, dtype: int64

In [8]:
# Converte de string para valor numérico
df_dsa["LABEL_TARGET"] = df_dsa["LABEL_TARGET"].astype(int)

In [9]:
# Visualizando alguns registros
df_dsa.head()

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X170,X171,X172,X173,X174,X175,X176,X177,X178,LABEL_TARGET
0,135,190,229,223,192,125,55,-9,-33,-38,...,-17,-15,-31,-77,-103,-127,-116,-83,-51,0
1,386,382,356,331,320,315,307,272,244,232,...,164,150,146,152,157,156,154,143,129,1
2,-32,-39,-47,-37,-32,-36,-57,-73,-85,-94,...,57,64,48,19,-12,-30,-35,-35,-36,0
3,-105,-101,-96,-92,-89,-95,-102,-100,-87,-79,...,-82,-81,-80,-77,-85,-77,-72,-69,-65,0
4,-9,-65,-98,-102,-78,-48,-16,0,-21,-59,...,4,2,-12,-32,-41,-65,-83,-89,-73,0

In [10]:
print("Número de colunas:", len(df_dsa.columns))

Número de colunas: 179

In [11]:
# Resumo estatístico
df_dsa.describe()

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X170,X171,X172,X173,X174,X175,X176,X177,X178,LABEL_TARGET
count,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000,11500.00000,11500.00000,11500.000000,...,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000
mean,-11.581391,-10.911565,-10.187130,-9.143043,-8.009739,-7.003478,-6.502087,-6.68713,-6.55800,-6.168435,...,-10.145739,-11.630348,-12.943478,-13.668870,-13.363304,-13.045043,-12.705130,-12.426000,-12.195652,0.200000
std,165.626284,166.059609,163.524317,161.269041,160.998007,161.328725,161.467837,162.11912,162.03336,160.436352,...,164.652883,166.149790,168.554058,168.556486,167.257290,164.241019,162.895832,162.886311,164.852015,0.400017
min,-1839.000000,-1838.000000,-1835.000000,-1845.000000,-1791.000000,-1757.000000,-1832.000000,-1778.00000,-1840.00000,-1867.000000,...,-1867.000000,-1865.000000,-1642.000000,-1723.000000,-1866.000000,-1863.000000,-1781.000000,-1727.000000,-1829.000000,0.000000
25%,-54.000000,-55.000000,-54.000000,-54.000000,-54.000000,-54.000000,-54.000000,-55.00000,-55.00000,-54.000000,...,-55.000000,-56.000000,-56.000000,-56.000000,-55.000000,-56.000000,-55.000000,-55.000000,-55.000000,0.000000
50%,-8.000000,-8.000000,-7.000000,-8.000000,-8.000000,-8.000000,-8.000000,-8.00000,-7.00000,-7.000000,...,-9.000000,-10.000000,-10.000000,-10.000000,-10.000000,-9.000000,-9.000000,-9.000000,-9.000000,0.000000
75%,34.000000,35.000000,36.000000,36.000000,35.000000,36.000000,35.000000,36.00000,36.00000,35.250000,...,34.000000,34.000000,33.000000,33.000000,34.000000,34.000000,34.000000,34.000000,34.000000,0.000000
max,1726.000000,1713.000000,1697.000000,1612.000000,1518.000000,1816.000000,2047.000000,2047.00000,2047.00000,2047.000000,...,1777.000000,1472.000000,1319.000000,1436.000000,1733.000000,1958.000000,2047.000000,2047.000000,1915.000000,1.000000

In [12]:
# Verificando se há valores ausentes
df_dsa.isnull().values.any()

np.False_

In [13]:
# Extrai a lista de colunas
lista_de_colunas = df_dsa.columns.tolist()

In [14]:
# Colunas das variáveis de entrada (input)
colunas_entrada = lista_de_colunas[0:178]

In [15]:
print(colunas_entrada)

['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X10', 'X11', 'X12', 'X13', 'X14', 'X15', 'X16', 'X17', 'X18', 'X19', 'X20', 'X21', 'X22', 'X23', 'X24', 'X25', 'X26', 'X27', 'X28', 'X29', 'X30', 'X31', 'X32', 'X33', 'X34', 'X35', 'X36', 'X37', 'X38', 'X39', 'X40', 'X41', 'X42', 'X43', 'X44', 'X45', 'X46', 'X47', 'X48', 'X49', 'X50', 'X51', 'X52', 'X53', 'X54', 'X55', 'X56', 'X57', 'X58', 'X59', 'X60', 'X61', 'X62', 'X63', 'X64', 'X65', 'X66', 'X67', 'X68', 'X69', 'X70', 'X71', 'X72', 'X73', 'X74', 'X75', 'X76', 'X77', 'X78', 'X79', 'X80', 'X81', 'X82', 'X83', 'X84', 'X85', 'X86', 'X87', 'X88', 'X89', 'X90', 'X91', 'X92', 'X93', 'X94', 'X95', 'X96', 'X97', 'X98', 'X99', 'X100', 'X101', 'X102', 'X103', 'X104', 'X105', 'X106', 'X107', 'X108', 'X109', 'X110', 'X111', 'X112', 'X113', 'X114', 'X115', 'X116', 'X117', 'X118', 'X119', 'X120', 'X121', 'X122', 'X123', 'X124', 'X125', 'X126', 'X127', 'X128', 'X129', 'X130', 'X131', 'X132', 'X133', 'X134', 'X135', 'X136', 'X137', 'X138', 'X139', 'X140', 'X141', 'X142', 'X143', 'X144', 'X145', 'X146', 'X147', 'X148', 'X149', 'X150', 'X151', 'X152', 'X153', 'X154', 'X155', 'X156', 'X157', 'X158', 'X159', 'X160', 'X161', 'X162', 'X163', 'X164', 'X165', 'X166', 'X167', 'X168', 'X169', 'X170', 'X171', 'X172', 'X173', 'X174', 'X175', 'X176', 'X177', 'X178']

In [16]:
# Checando se temos colunas duplicadas nos dados de entrada
dup_cols = set([x for x in colunas_entrada if colunas_entrada.count(x) > 1])
print(dup_cols)
assert len(dup_cols) == 0, "você duplicou colunas em cols_input"

set()

In [17]:
# Checando se temos colunas duplicadas no dataset completo
dup_cols = set([x for x in lista_de_colunas if lista_de_colunas.count(x) > 1])
print(dup_cols)
assert len(dup_cols) == 0,'você duplicou colunas em lista_de_colunas'

set()

In [18]:
# Categorias da variável alvo
df_dsa.LABEL_TARGET.value_counts()

LABEL_TARGET
0    9200
1    2300
Name: count, dtype: int64

A prevalência é a porcentagem das amostras que têm a característica que você está tentando prever. Em nosso caso, significa que as pessoas que renovaram o seguro são da classe positiva (ocorrência do evento) e quem não comprou é da classe negativa (não ocorreu o evento).

Os termos positivo e negativo não têm conotação de coisa boa ou ruim. É apenas a nomenclatura usada para indicar a ocorrência ou não do evento.

A taxa é calculada por (número de amostras positivas / número de amostras). Portanto, uma taxa de prevalência de 0,2 significa que 20% de nossa amostra renovou o seguro do carro.

In [19]:
# Esta função calcula a prevalência da classe positiva (label = 1)
def calcula_prevalencia(y_actual):
    return sum(y_actual) / len(y_actual)

In [20]:
print("Prevalência da classe positiva: %.3f"% calcula_prevalencia(df_dsa["LABEL_TARGET"].values))

Prevalência da classe positiva: 0.200

> O desbalanceamento de classe é um problema que terá que ser resolvido durante o pré-processamento dos dados.

## Divisão dos Dados Mantendo a Prevalência de Classe

In [21]:
# Gerando amostras aleatórias dos dados
df_data = df_dsa.sample(n = len(df_dsa))

In [22]:
df_data

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X170,X171,X172,X173,X174,X175,X176,X177,X178,LABEL_TARGET
2040,10,10,10,10,-1,-7,-9,-16,-13,-20,...,84,89,99,106,106,104,99,99,93,0
1749,-202,-255,-314,-391,-432,-322,-134,136,323,427,...,293,278,248,219,197,166,129,78,14,1
1029,-208,-203,-158,-103,-38,34,113,187,244,280,...,-137,-143,-153,-148,-117,-82,-44,-28,-18,1
2088,53,39,21,0,-10,-28,-42,-58,-76,-93,...,-79,-79,-80,-83,-74,-64,-57,-53,-57,0
3200,-47,-54,-44,-39,-39,-50,-81,-75,-68,-53,...,-153,-187,-194,-176,-154,-121,-87,-53,-9,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7467,-3,-5,-7,-13,-9,-15,-30,-58,-87,-114,...,-68,-59,-39,-27,-19,-13,-5,-3,-1,0
1754,-23,-16,-10,3,8,12,8,15,15,24,...,-48,-55,-60,-61,-61,-53,-47,-43,-38,0
5639,-37,-44,-48,-46,-45,-47,-47,-53,-58,-67,...,-23,-22,-26,-30,-35,-36,-42,-39,-32,0
5739,-15,-21,-37,-34,-8,23,42,63,60,64,...,-3,-35,-24,-8,25,44,52,51,49,0
8664,-448,-332,-251,-178,-84,4,90,132,141,116,...,388,311,200,71,-62,-168,-205,-119,17,1

In [23]:
# Ajustando os índices do dataset
df_data = df_data.reset_index(drop = True)

In [24]:
df_data

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X170,X171,X172,X173,X174,X175,X176,X177,X178,LABEL_TARGET
0,10,10,10,10,-1,-7,-9,-16,-13,-20,...,84,89,99,106,106,104,99,99,93,0
1,-202,-255,-314,-391,-432,-322,-134,136,323,427,...,293,278,248,219,197,166,129,78,14,1
2,-208,-203,-158,-103,-38,34,113,187,244,280,...,-137,-143,-153,-148,-117,-82,-44,-28,-18,1
3,53,39,21,0,-10,-28,-42,-58,-76,-93,...,-79,-79,-80,-83,-74,-64,-57,-53,-57,0
4,-47,-54,-44,-39,-39,-50,-81,-75,-68,-53,...,-153,-187,-194,-176,-154,-121,-87,-53,-9,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11495,-3,-5,-7,-13,-9,-15,-30,-58,-87,-114,...,-68,-59,-39,-27,-19,-13,-5,-3,-1,0
11496,-23,-16,-10,3,8,12,8,15,15,24,...,-48,-55,-60,-61,-61,-53,-47,-43,-38,0
11497,-37,-44,-48,-46,-45,-47,-47,-53,-58,-67,...,-23,-22,-26,-30,-35,-36,-42,-39,-32,0
11498,-15,-21,-37,-34,-8,23,42,63,60,64,...,-3,-35,-24,-8,25,44,52,51,49,0
11499,-448,-332,-251,-178,-84,4,90,132,141,116,...,388,311,200,71,-62,-168,-205,-119,17,1

In [25]:
# Extrai uma amostra de 30% dos dados de forma aleatória
df_amostra_30 = df_data.sample(frac = 0.3)

In [26]:
df_amostra_30

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X170,X171,X172,X173,X174,X175,X176,X177,X178,LABEL_TARGET
7900,50,29,12,-7,-36,-58,-63,-49,-48,-47,...,76,92,88,77,68,51,17,-23,-59,0
10027,-1,18,33,35,26,25,22,20,21,30,...,82,71,62,57,54,35,12,-6,-22,0
2187,37,97,121,122,117,108,93,63,38,11,...,11,24,26,17,14,18,29,36,22,0
9389,-73,-87,-66,-19,10,-11,-51,-68,-44,8,...,-10,10,17,16,14,20,34,52,84,0
7353,-61,-54,-65,-48,-41,-14,-2,18,43,58,...,-64,-53,-46,-51,-55,-55,-48,-46,-61,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11392,-94,-116,-91,-94,-68,-50,-7,43,53,34,...,-73,-78,-61,-49,-24,14,44,86,105,0
1441,-55,-54,-60,-57,-47,-32,-18,-10,2,9,...,54,53,47,22,-10,-29,-38,-34,-35,0
1452,37,28,21,8,2,6,20,37,45,60,...,-50,-64,-66,-73,-82,-83,-65,-24,4,0
2603,81,60,31,8,-1,8,28,45,47,38,...,75,86,84,78,65,57,50,39,27,0
628,-134,-145,-120,-69,-57,-62,-79,-89,-47,-48,...,24,18,14,38,44,25,-12,-30,-9,0

In [27]:
print("Tamanho da divisão de validação / teste: %.1f" % (len(df_amostra_30) / len(df_data)))

Tamanho da divisão de validação / teste: 0.3

In [28]:
# Fazendo a divisão

# Dados de teste
df_teste = df_amostra_30.sample(frac = 0.5)

# Dados se validação
df_valid = df_amostra_30.drop(df_teste.index)

# Dados de treino
df_treino = df_data.drop(df_amostra_30.index)

In [29]:
df_teste

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X170,X171,X172,X173,X174,X175,X176,X177,X178,LABEL_TARGET
11075,634,688,542,272,-88,-485,-656,-586,-360,-75,...,-333,90,303,383,357,239,105,8,-22,1
1254,-16,0,8,0,-13,-15,-8,-8,-9,-8,...,25,19,33,42,37,16,-7,-18,-28,0
5296,-278,-301,-319,-385,-414,-446,-388,-238,-138,60,...,-313,-217,-29,160,337,463,493,493,444,1
1183,0,-11,-14,-19,-30,-50,-72,-100,-125,-131,...,-20,-19,2,14,18,15,-9,-24,-32,0
217,-11,-23,-31,-39,-28,-15,-3,17,28,35,...,62,62,61,62,63,70,79,84,84,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6472,24,18,15,8,3,-7,-6,-6,-15,-24,...,-36,-31,-25,-6,11,12,-2,-13,-10,0
3328,-105,-101,-96,-92,-86,-78,-70,-69,-72,-65,...,-19,-39,-39,-35,-24,-28,-22,-16,-20,0
10655,-212,-246,-233,-191,-133,-76,-29,-1,22,44,...,8,-3,-20,-36,-53,-68,-74,-63,-38,1
1529,75,45,15,-9,-45,-71,-86,-93,-92,-88,...,5,1,-5,-7,2,16,6,-16,-62,0
6121,-253,-327,-376,-365,-319,-250,-135,-15,58,54,...,-18,-18,-20,-23,-27,-29,-39,-40,-44,1

In [30]:
df_valid

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X170,X171,X172,X173,X174,X175,X176,X177,X178,LABEL_TARGET
2187,37,97,121,122,117,108,93,63,38,11,...,11,24,26,17,14,18,29,36,22,0
9389,-73,-87,-66,-19,10,-11,-51,-68,-44,8,...,-10,10,17,16,14,20,34,52,84,0
7647,8,12,14,12,5,1,2,8,11,14,...,-139,-136,-133,-127,-127,-130,-134,-131,-126,0
8809,-6,-44,-82,-105,-113,-96,-62,-25,0,31,...,-144,-146,-146,-142,-134,-133,-128,-123,-112,1
69,-98,-93,-80,-65,-52,-41,-29,-21,-40,-53,...,-31,-16,1,12,18,7,-1,-1,10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6041,-52,-8,20,18,-2,-7,-26,-51,-91,-122,...,-20,4,29,46,56,57,54,57,50,0
8994,23,18,20,20,27,15,0,-11,-6,5,...,-73,-78,-75,-66,-62,-49,-47,-51,-53,0
11392,-94,-116,-91,-94,-68,-50,-7,43,53,34,...,-73,-78,-61,-49,-24,14,44,86,105,0
1441,-55,-54,-60,-57,-47,-32,-18,-10,2,9,...,54,53,47,22,-10,-29,-38,-34,-35,0
1452,37,28,21,8,2,6,20,37,45,60,...,-50,-64,-66,-73,-82,-83,-65,-24,4,0

In [31]:
df_treino

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X170,X171,X172,X173,X174,X175,X176,X177,X178,LABEL_TARGET
1,-202,-255,-314,-391,-432,-322,-134,136,323,427,...,293,278,248,219,197,166,129,78,14,1
2,-208,-203,-158,-103,-38,34,113,187,244,280,...,-137,-143,-153,-148,-117,-82,-44,-28,-18,1
3,53,39,21,0,-10,-28,-42,-58,-76,-93,...,-79,-79,-80,-83,-74,-64,-57,-53,-57,0
4,-47,-54,-44,-39,-39,-50,-81,-75,-68,-53,...,-153,-187,-194,-176,-154,-121,-87,-53,-9,0
5,-71,-96,-110,-88,-47,-1,24,21,2,-13,...,-70,-70,-83,-97,-100,-96,-87,-69,-59,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11491,291,263,214,162,106,64,30,7,-1,-7,...,77,123,154,186,160,-17,-534,-1007,-1316,1
11492,-123,80,234,299,257,133,-71,-253,-405,-535,...,-463,-362,-295,-263,-237,-202,-153,-97,-37,1
11494,190,198,198,193,192,179,167,143,122,95,...,-64,-52,-24,2,15,17,16,9,-6,0
11497,-37,-44,-48,-46,-45,-47,-47,-53,-58,-67,...,-23,-22,-26,-30,-35,-36,-42,-39,-32,0
11498,-15,-21,-37,-34,-8,23,42,63,60,64,...,-3,-35,-24,-8,25,44,52,51,49,0

In [32]:
# Verifique a prevalência de cada subconjunto
print(
    "Teste(n = %d): %.3f"
    % (len(df_teste), calcula_prevalencia(df_teste.LABEL_TARGET.values))
)
print(
    "Validação(n = %d): %.3f"
    % (len(df_valid), calcula_prevalencia(df_valid.LABEL_TARGET.values))
)
print(
    "Treino(n = %d): %.3f"
    % (len(df_treino), calcula_prevalencia(df_treino.LABEL_TARGET.values))
)

Teste(n = 1725): 0.195
Validação(n = 1725): 0.205
Treino(n = 8050): 0.200

## Balanceamento de Classe

Vamos aplicar a estratégia de undersampling. Leia o material no Capítulo 8 com a definição dos conceitos.

In [33]:
df_teste.shape

(1725, 179)

In [34]:
df_valid.shape

(1725, 179)

In [35]:
df_treino.shape

(8050, 179)

In [36]:
df_treino.LABEL_TARGET.value_counts()

LABEL_TARGET
0    6441
1    1609
Name: count, dtype: int64

In [37]:
# Cria um índice com True/False
indice = df_treino.LABEL_TARGET == 1

In [38]:
# Define valores positivos e negativos do índice
df_train_pos = df_treino.loc[indice]
df_train_neg = df_treino.loc[~indice]

In [39]:
# Valor mínimo de registros entre classe positiva e negativa
valor_minimo = np.min([len(df_train_pos), len(df_train_neg)])

In [40]:
valor_minimo

np.int64(1609)

In [41]:
# Obtém valores aleatórios para o dataset de treino
df_treino_final = pd.concat([df_train_pos.sample(n = valor_minimo, random_state = 69), 
                             df_train_neg.sample(n = valor_minimo, random_state = 69)], 
                            axis = 0, 
                            ignore_index = True)

In [42]:
# Amostragem aleatória do dataset de treino
df_treino_final = df_treino_final.sample(n = len(df_treino_final), random_state = 69).reset_index(drop = True)

In [43]:
df_treino_final.shape

(3218, 179)

In [44]:
df_treino_final.LABEL_TARGET.value_counts()

LABEL_TARGET
1    1609
0    1609
Name: count, dtype: int64

In [45]:
# Balanceamento do conjunto de dados
print('Balanceamento em Treino(n = %d): %.3f'%(len(df_treino_final), 
                                               calcula_prevalencia(df_treino_final.LABEL_TARGET.values)))

Balanceamento em Treino(n = 3218): 0.500

## Salvando o Resultado do Pré-Processamento

In [46]:
# Salvamos todos os datasets em disco no formato csv
df_treino.to_csv('dados/dados_treino.csv', index = False)
df_treino_final.to_csv('dados/dados_treino_final.csv', index = False)
df_valid.to_csv('dados/dados_valid.csv', index = False)
df_teste.to_csv('dados/dados_teste.csv', index = False)

In [47]:
# Salvamos os nomes dos dados de entrada (colunas preditoras) para facilitar a utilização mais tarde
pickle.dump(colunas_entrada, open('dados/colunas_entrada.sav', 'wb'))

# Continuaremos o Projeto no Próximo Capítulo!

In [48]:
%reload_ext watermark
%watermark -a "Data Science Academy"

Author: Data Science Academy

In [49]:
#%watermark -v -m

In [50]:
#%watermark --iversions

# Fim