<!-- Projeto Desenvolvido na Data Science Academy - www.datascienceacademy.com.br -->
# <font color='blue'>Data Science Academy</font>
## <font color='blue'>Data Science Para Análise Multivariada de Dados</font>
## <font color='blue'>Projeto 9</font>
### <font color='blue'>Data Science no Agronegócio</font>
### <font color='blue'>Previsão de Rendimento de Colheita e Otimização da Irrigação</font>

## Instalando e Carregando os Pacotes
<!-- Projeto Desenvolvido na Data Science Academy - www.datascienceacademy.com.br -->

In [1]:
!pip install -q -U watermark

https://www.tensorflow.org/

In [2]:
%env TF_CPP_MIN_LOG_LEVEL=3

env: TF_CPP_MIN_LOG_LEVEL=3

In [3]:
# Imports
import joblib
import sklearn
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
import warnings
warnings.filterwarnings('ignore')

In [4]:
%reload_ext watermark
%watermark -a "Data Science Academy"

Author: Data Science Academy

## Carregando o Conjunto de Dados

In [5]:
# Carregar o dataset
df_dsa = pd.read_csv('dataset.csv')

In [6]:
df_dsa.shape

(124, 12)

In [7]:
df_dsa.head()

,data,indice_vegetacao,capacidade_solo,concentracao_co2,nivel_nutrientes,indice_fertilizantes,profundidade_raiz,radiacao_solar,precipitacao,estagio_crescimento,historico_rendimento,umidade
0,2012-12-01,323,455,3102.61,423.45,844.0,468.0,578.0,28.67,207.70504,117.7,79.261905
1,2013-01-01,345,546,3100.45,415.85,799.0,485.0,557.0,24.49,228.94287,4.5,82.193548
2,2013-02-01,362,595,3199.41,410.77,718.0,466.0,552.0,22.06,238.41747,25.1,74.839286
3,2013-03-01,376,636,3281.67,414.82,614.0,442.0,574.0,21.64,218.47599,53.6,77.935484
4,2013-04-01,383,738,3261.65,451.04,619.0,429.0,595.0,22.30,226.15010,166.0,80.450000

In [8]:
df_dsa.tail()

,data,indice_vegetacao,capacidade_solo,concentracao_co2,nivel_nutrientes,indice_fertilizantes,profundidade_raiz,radiacao_solar,precipitacao,estagio_crescimento,historico_rendimento,umidade
119,2022-11-01,362,363,2626.91,1252.78,738.07,427.49,1430.48,60.18,186.68326,38.2,77.950000
120,2022-12-01,310,322,2736.64,1287.68,749.57,385.09,1472.27,62.25,210.72987,33.7,76.177419
121,2023-01-01,277,307,2842.81,1289.12,761.60,373.03,1525.43,63.04,244.41912,4.6,74.774194
122,2023-02-01,323,330,2936.19,1303.59,759.59,390.69,1572.25,71.52,223.31732,6.9,66.910714
123,2023-03-01,360,339,2847.84,1234.88,771.62,396.87,1302.61,74.80,228.56676,41.5,69.000000

## Análise Exploratória

In [9]:
# Verificar os tipos de dados das colunas
df_dsa.dtypes

data                     object
indice_vegetacao          int64
capacidade_solo           int64
concentracao_co2        float64
nivel_nutrientes        float64
indice_fertilizantes    float64
profundidade_raiz       float64
radiacao_solar          float64
precipitacao            float64
estagio_crescimento     float64
historico_rendimento    float64
umidade                 float64
dtype: object

In [10]:
# Exibir as colunas do dataset
df_dsa.columns

Index(['data', 'indice_vegetacao', 'capacidade_solo', 'concentracao_co2',
       'nivel_nutrientes', 'indice_fertilizantes', 'profundidade_raiz',
       'radiacao_solar', 'precipitacao', 'estagio_crescimento',
       'historico_rendimento', 'umidade'],
      dtype='object')

In [11]:
# Identificar colunas não numéricas
non_numeric_columns = df_dsa.select_dtypes(include = ['object']).columns
print(f'Colunas não numéricas: {non_numeric_columns}')

Colunas não numéricas: Index(['data'], dtype='object')

## Limpeza e Transformação

In [12]:
# Remover colunas não numéricas (se não forem necessárias)
df_dsa = df_dsa.drop(columns = non_numeric_columns)

In [13]:
# Verificar se a coluna 'umidade' contém valores numéricos
if df_dsa['umidade'].dtype == 'object':
    df_dsa['umidade'] = pd.to_numeric(df_dsa['umidade'], errors = 'coerce')

In [14]:
# Remover linhas com valores faltantes
df_dsa = df_dsa.dropna()

## Padronização dos Dados

In [15]:
# Separar preditores e variável alvo
X = df_dsa.drop(columns = 'umidade')
y = df_dsa['umidade']

In [16]:
# Dividir os dados em conjunto de treino e teste
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [17]:
# Cria o padronizador
scaler = StandardScaler()

In [18]:
# Padroniza os dados
X_treino_scaled = scaler.fit_transform(X_treino)
X_teste_scaled = scaler.transform(X_teste)

In [19]:
# Salva o padronizador no disco
joblib.dump(scaler, 'scaler_dsa.joblib')

['scaler_dsa.joblib']

## Construção do Modelo

Acompanhe os detalhes no videobook do Capítulo 19.

In [20]:
# Definir a arquitetura do modelo
modelo_dsa = Sequential([Dense(64, activation = 'relu', input_shape = (X_treino.shape[1],)),
                         Dropout(0.3),
                         Dense(32, activation = 'relu'),
                         Dropout(0.3),
                         Dense(16, activation = 'relu'),
                         Dense(1)])

O código acima define a arquitetura de um modelo de rede neural sequencial utilizando a biblioteca Keras. Aqui está uma explicação detalhada de cada linha:

**modelo_dsa = Sequential([ ... ])**: Cria um modelo sequencial, que é uma pilha linear de camadas.

**Dense(64, activation='relu', input_shape=(X_treino.shape[1],))**: Adiciona uma camada densa (totalmente conectada) com 64 neurônios e função de ativação ReLU (Rectified Linear Unit). A input_shape especifica a forma dos dados de entrada, que corresponde ao número de características (colunas) em X_treino.

**Dropout(0.3)**: Adiciona uma camada de dropout com uma taxa de 30%. Dropout é uma técnica de regularização que desativa aleatoriamente 30% dos neurônios durante o treinamento para prevenir o overfitting.

**Dense(32, activation='relu')**: Adiciona outra camada densa com 32 neurônios e função de ativação ReLU.

**Dropout(0.3)**: Adiciona mais uma camada de dropout com uma taxa de 30%.

**Dense(16, activation='relu')**: Adiciona mais uma camada densa com 16 neurônios e função de ativação ReLU.

**Dense(1)**: Adiciona a camada de saída com um único neurônio. Não é especificada uma função de ativação, o que é comum em problemas de regressão, onde a saída é um valor contínuo. Se fosse um problema de classificação binária, uma ativação sigmoid poderia ser usada nesta camada.

Essa arquitetura é típica para problemas de regressão onde se deseja prever um único valor contínuo a partir de múltiplas características de entrada.

## Compilação do Modelo

Acompanhe os detalhes no videobook do Capítulo 19.

In [21]:
# Compilar o modelo
modelo_dsa.compile(optimizer = 'adam', loss = 'mse', metrics = ['mae'])

O código acima compila o modelo de rede neural que foi definido anteriormente. A compilação é um passo necessário antes de treinar o modelo. Aqui está uma explicação de cada parte do código:

**modelo_dsa.compile(...)**: Compila o modelo, configurando-o para treinamento com um otimizador, uma função de perda e métricas.

**optimizer='adam'**: Define o otimizador como 'adam'. O Adam (Adaptive Moment Estimation) é um otimizador eficiente e amplamente utilizado em redes neurais, combinando as vantagens dos algoritmos de Gradient Descent com Momentum e RMSProp. Ele ajusta dinamicamente a taxa de aprendizado durante o treinamento.

**loss='mse'**: Define a função de perda como 'mse' (Mean Squared Error). MSE é uma função de perda comum em problemas de regressão, que calcula a média dos quadrados das diferenças entre os valores previstos e os valores reais. É usada para medir o desempenho do modelo, com valores menores indicando um melhor ajuste.

**metrics=['mae']**: Especifica que a métrica a ser monitorada durante o treinamento é 'mae' (Mean Absolute Error). MAE é a média dos valores absolutos das diferenças entre os valores previstos e os valores reais. Assim como MSE, valores menores de MAE indicam um melhor desempenho do modelo, mas MAE é menos sensível a grandes erros do que MSE.

Compilar o modelo é um passo essencial que define como o modelo será otimizado e avaliado durante o treinamento.

## Definindo os Callbacks

Acompanhe os detalhes no videobook do Capítulo 19.

In [22]:
# Callbacks
early_stopping = EarlyStopping(monitor = 'val_loss', patience = 10, restore_best_weights = True)
model_checkpoint = ModelCheckpoint('modelo_dsa.keras', save_best_only = True)

Este trecho de código define dois callbacks para o treinamento do modelo: EarlyStopping e ModelCheckpoint. Callbacks são ferramentas que permitem realizar certas ações em pontos específicos durante o treinamento.

**early_stopping = EarlyStopping(...)**: Define um callback de parada antecipada (early stopping).

**monitor='val_loss'**: Monitora a perda de validação (val_loss) durante o treinamento. A validação é um processo onde um conjunto separado de dados (dados de validação) é usado para avaliar o desempenho do modelo, ajudando a evitar o overfitting.

**patience=10**: Define a paciência em 10 épocas. Isso significa que se a perda de validação não melhorar por 10 épocas consecutivas, o treinamento será interrompido.

**restore_best_weights=True**: Restabelece os pesos do modelo para o estado em que apresentaram a melhor perda de validação. Isso garante que os pesos finais do modelo sejam os melhores encontrados durante o treinamento.

**model_checkpoint = ModelCheckpoint(...)**: Define um callback de checkpoint do modelo.

**'modelo_dsa.keras'**: Especifica o nome do arquivo onde o modelo será salvo.

**save_best_only=True**: Salva o modelo apenas quando ele apresentar a melhor perda de validação até o momento. Isso evita salvar várias versões do modelo e garante que o melhor modelo encontrado durante o treinamento seja salvo.

Em resumo, esses callbacks ajudam a:

- Parar o treinamento antecipadamente se o modelo não estiver melhorando, economizando tempo e recursos computacionais.

- Salvar automaticamente o melhor modelo encontrado durante o treinamento, garantindo que você tenha uma versão do modelo com o melhor desempenho.

## Treinamento do Modelo

In [23]:
modelo_dsa.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           704 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,329 (13.00 KB)

 Trainable params: 3,329 (13.00 KB)

 Non-trainable params: 0 (0.00 B)

In [24]:
# Treinar o modelo
history = modelo_dsa.fit(X_treino_scaled, 
                         y_treino,
                         validation_split = 0.2,
                         epochs = 100,
                         batch_size = 32,
                         callbacks = [early_stopping, model_checkpoint])

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 5243.3618 - mae: 72.2740 - val_loss: 5221.4834 - val_mae: 72.1553
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5222.7026 - mae: 72.1333 - val_loss: 5200.7710 - val_mae: 72.0121
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5201.0928 - mae: 71.9861 - val_loss: 5180.0186 - val_mae: 71.8685
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5123.0073 - mae: 71.4251 - val_loss: 5158.1045 - val_mae: 71.7163
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5169.5020 - mae: 71.7646 - val_loss: 5134.4302 - val_mae: 71.5512
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5112.0176 - mae: 71.3507 - val_loss: 5108.1807 - val_mae: 71.3677
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5081.5898 - mae: 71.1247 - val_loss: 5079.2373 - val_mae: 71.1646
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5100.3521 - mae: 71.2580 - val_loss: 5046.6533 - val_mae: 70.9351
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4983.4634 - mae: 70.4528 - val_loss: 5010.5884 - val_mae: 70.6802
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5008.3906 - mae: 70.6288 - val_loss: 4970.8794 - val_mae: 70.3986
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4956.5596 - mae: 70.2379 - val_loss: 4925.5815 - val_mae: 70.0759
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4909.5752 - mae: 69.9040 - val_loss: 4875.3047 - val_mae: 69.7160
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4862.4458 - mae: 69.5611 - val_loss: 4819.0796 - val_mae: 69.3111
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4836.2188 - mae: 69.3754 - val_loss: 4755.7344 - val_mae: 68.8520
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 4681.4663 - mae: 68.2492 - val_loss: 4684.2656 - val_mae: 68.3300
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4619.4741 - mae: 67.7841 - val_loss: 4603.4429 - val_mae: 67.7347
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4554.7563 - mae: 67.2904 - val_loss: 4511.2407 - val_mae: 67.0488
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 4498.7842 - mae: 66.8742 - val_loss: 4407.6162 - val_mae: 66.2691
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 4323.8701 - mae: 65.5100 - val_loss: 4291.3179 - val_mae: 65.3826
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4231.4033 - mae: 64.8073 - val_loss: 4160.7671 - val_mae: 64.3720
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 4124.9297 - mae: 64.0014 - val_loss: 4016.4839 - val_mae: 63.2357
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 3915.0542 - mae: 62.2685 - val_loss: 3855.7800 - val_mae: 61.9437
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 3705.6694 - mae: 60.5651 - val_loss: 3677.1653 - val_mae: 60.4736
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 3645.5776 - mae: 59.9600 - val_loss: 3482.1021 - val_mae: 58.8250
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 3351.1030 - mae: 57.5018 - val_loss: 3268.1780 - val_mae: 56.9586
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3128.4946 - mae: 55.4575 - val_loss: 3037.3879 - val_mae: 54.8704
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2837.3376 - mae: 52.6929 - val_loss: 2790.4780 - val_mae: 52.5395
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2723.3657 - mae: 51.3349 - val_loss: 2534.5366 - val_mae: 50.0016
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2430.2278 - mae: 48.3050 - val_loss: 2268.9519 - val_mae: 47.2168
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2258.1724 - mae: 46.4496 - val_loss: 1998.4880 - val_mae: 44.1910
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1883.8789 - mae: 42.0456 - val_loss: 1730.3047 - val_mae: 40.9611
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1709.4415 - mae: 39.6230 - val_loss: 1467.6062 - val_mae: 37.5144
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1269.2281 - mae: 32.6896 - val_loss: 1218.9584 - val_mae: 33.9226
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1169.3876 - mae: 31.0357 - val_loss: 988.6836 - val_mae: 30.2072
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 887.7543 - mae: 26.7416 - val_loss: 781.3129 - val_mae: 26.3974
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 825.1215 - mae: 25.6386 - val_loss: 605.2097 - val_mae: 22.6657
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 641.0038 - mae: 22.4992 - val_loss: 457.9500 - val_mae: 19.0280
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 562.5159 - mae: 20.1454 - val_loss: 345.0098 - val_mae: 16.0803
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 425.2485 - mae: 17.3753 - val_loss: 264.4385 - val_mae: 13.7711
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 478.5305 - mae: 18.0201 - val_loss: 207.1622 - val_mae: 11.7109
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 386.8420 - mae: 15.9401 - val_loss: 170.8000 - val_mae: 10.0263
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 380.3050 - mae: 15.7628 - val_loss: 147.6858 - val_mae: 9.1402
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 344.8788 - mae: 13.7231 - val_loss: 136.4305 - val_mae: 8.6558
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 420.0042 - mae: 15.3332 - val_loss: 133.5626 - val_mae: 8.4627
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 391.8346 - mae: 16.2731 - val_loss: 135.6629 - val_mae: 8.6330
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 318.3038 - mae: 14.4056 - val_loss: 140.8407 - val_mae: 8.8827
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 266.9828 - mae: 13.3240 - val_loss: 147.9549 - val_mae: 9.2472
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 273.6473 - mae: 14.1260 - val_loss: 155.7482 - val_mae: 9.6202
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 278.3117 - mae: 14.0438 - val_loss: 159.5725 - val_mae: 9.8533
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 268.7860 - mae: 13.5045 - val_loss: 160.5296 - val_mae: 9.9183
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 366.3259 - mae: 16.0200 - val_loss: 159.8921 - val_mae: 9.8727
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 350.7137 - mae: 14.7989 - val_loss: 159.2799 - val_mae: 9.8701
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 276.6132 - mae: 12.8954 - val_loss: 158.8801 - val_mae: 9.8862
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 302.3170 - mae: 14.0619 - val_loss: 156.5939 - val_mae: 9.8418

Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 335.0539 - mae: 14.5242 - val_loss: 222.9784 - val_mae: 11.6431
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 308.2426 - mae: 14.6575 - val_loss: 222.2989 - val_mae: 11.7496
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 282.5726 - mae: 14.0260 - val_loss: 220.2920 - val_mae: 11.8014
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 514.7080 - mae: 18.0674 - val_loss: 217.4007 - val_mae: 11.8132
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 323.6817 - mae: 14.0053 - val_loss: 214.0239 - val_mae: 11.7764
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 321.5867 - mae: 14.9455 - val_loss: 210.1026 - val_mae: 11.6990
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 289.9587 - mae: 13.8244 - val_loss: 208.2907 - val_mae: 11.6739
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 452.1917 - mae: 16.0378 - val_loss: 204.8585 - val_mae: 11.5665
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 302.9095 - mae: 13.7919 - val_loss: 199.6939 - val_mae: 11.3909
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 295.3107 - mae: 14.0250 - val_loss: 191.6762 - val_mae: 11.0814
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 388.7861 - mae: 15.5307 - val_loss: 186.9229 - val_mae: 10.8965
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 297.5995 - mae: 14.5098 - val_loss: 185.5372 - val_mae: 10.8582
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 326.6629 - mae: 15.0098 - val_loss: 186.8722 - val_mae: 10.9113
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 329.8542 - mae: 14.8833 - val_loss: 188.4652 - val_mae: 10.9547
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 268.6307 - mae: 12.5872 - val_loss: 188.5700 - val_mae: 10.9283
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 242.6456 - mae: 12.2083 - val_loss: 187.6615 - val_mae: 10.8708
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 244.7195 - mae: 13.0404 - val_loss: 186.4831 - val_mae: 10.8086
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 304.0048 - mae: 13.8607 - val_loss: 184.2631 - val_mae: 10.7195
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 310.3225 - mae: 13.8209 - val_loss: 180.9753 - val_mae: 10.5631
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 359.5021 - mae: 15.3993 - val_loss: 179.2792 - val_mae: 10.4895
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 225.9000 - mae: 11.9312 - val_loss: 177.4437 - val_mae: 10.4126
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 314.4075 - mae: 13.8046 - val_loss: 173.9035 - val_mae: 10.3109
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 249.1360 - mae: 12.9323 - val_loss: 171.4546 - val_mae: 10.2411
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 258.7849 - mae: 13.4739 - val_loss: 170.2536 - val_mae: 10.2273
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 335.3040 - mae: 15.0242 - val_loss: 172.1169 - val_mae: 10.2732
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 440.6624 - mae: 16.8397 - val_loss: 174.6055 - val_mae: 10.3640
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 253.2719 - mae: 12.9476 - val_loss: 177.3037 - val_mae: 10.4533
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 284.7556 - mae: 13.0214 - val_loss: 179.0172 - val_mae: 10.4756
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 229.8471 - mae: 12.4517 - val_loss: 178.9960 - val_mae: 10.4315
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 278.2866 - mae: 13.1367 - val_loss: 177.9146 - val_mae: 10.3253
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 253.2754 - mae: 13.2047 - val_loss: 176.5470 - val_mae: 10.2383
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 272.1539 - mae: 13.0142 - val_loss: 176.2597 - val_mae: 10.1859
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 268.2182 - mae: 12.8298 - val_loss: 172.9633 - val_mae: 10.0170
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 318.9066 - mae: 14.9493 - val_loss: 168.6816 - val_mae: 9.8880
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 279.5510 - mae: 13.8106 - val_loss: 162.3892 - val_mae: 9.6888
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 309.4948 - mae: 14.5096 - val_loss: 157.8095 - val_mae: 9.5380
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 260.8180 - mae: 12.6727 - val_loss: 153.5132 - val_mae: 9.3897
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 260.8016 - mae: 12.1852 - val_loss: 148.2353 - val_mae: 9.2737
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 279.7042 - mae: 13.4866 - val_loss: 146.3946 - val_mae: 9.2302
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 213.9910 - mae: 11.7125 - val_loss: 147.3378 - val_mae: 9.2316
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 282.5454 - mae: 13.5540 - val_loss: 149.1236 - val_mae: 9.2603
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 220.2296 - mae: 11.7371 - val_loss: 152.3550 - val_mae: 9.3363
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 239.5569 - mae: 12.2760 - val_loss: 155.4454 - val_mae: 9.4184
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 297.2142 - mae: 14.0621 - val_loss: 156.2401 - val_mae: 9.4633
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 292.7177 - mae: 13.2105 - val_loss: 154.1414 - val_mae: 9.4430
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 331.1794 - mae: 14.9472 - val_loss: 149.8449 - val_mae: 9.3391
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 188.4146 - mae: 11.4343 - val_loss: 147.7701 - val_mae: 9.2840
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 227.1912 - mae: 12.2879 - val_loss: 146.2297 - val_mae: 9.2229

## Avaliação do Modelo

In [25]:
# Avaliar o modelo no conjunto de teste
teste_loss, teste_mae = modelo_dsa.evaluate(X_teste_scaled, y_teste)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 133.9822 - mae: 9.3285

In [26]:
print(f'Teste Loss: {teste_loss}')
print(f'Teste MAE: {teste_mae}')

Teste Loss: 133.98216247558594
Teste MAE: 9.328458786010742

Vamos agora fazer o deploy do modelo via API no próximo capítulo.

In [27]:
%reload_ext watermark
%watermark -a "Data Science Academy"

Author: Data Science Academy

In [28]:
#%watermark -v -m

In [29]:
#%watermark --iversions

# Fim